TICKERS = ['ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALBK', 'ALNU', 'ALRS', 'AMEZ', 'APTK', 'AQUA', 'ARSA',
		   'ASSB', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISV', 'BISVP', 'BLNG', 'BRZL', 'BSPB', 'BSPBP', 'CBOM',
		   'CHEP',
		   'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CNTL', 'CNTLP', 'DERZP', 'DIOD', 'DSKY', 'DVEC', 'DZRD', 'DZRDP',
		   'EELT',
		   'ELTZ', 'ENPG', 'ENRU', 'ETLN', 'FEES', 'FESH', 'FIVE', 'FLOT', 'GAZA', 'GAZAP', 'GAZC', 'GAZP', 'GAZS',
		   'GAZT', 'GCHE', 'GEMA', 'GLTR', 'GMKN', 'GTRK', 'GTSS', 'HALS', 'HHRU', 'HIMC', 'HIMCP', 'HYDR', 'IGST',
		   'IGSTP', 'INGR', 'IRAO', 'IRGZ', 'IRKT', 'ISKJ', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KBTK',
		   'KCHE',
		   'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KMAZ', 'KMEZ', 'KMTZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKO', 'KRKOP',
		   'KROT',
		   'KROTP', 'KRSB', 'KRSBP', 'KSGR', 'KTSB', 'KTSBP', 'KUBE', 'KUNF', 'KUZB', 'KZMS', 'KZOS', 'KZOSP',
		   'LIFE',
		   'LKOH', 'LNTA', 'LNZL', 'LNZLP', 'LPSB', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN',
		   'MAIL',
		   'MDMG', 'MFGS', 'MFGSP', 'MFON', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOBB', 'MOEX',
		   'MORI',
		   'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR',
		   'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB',
		   'NNSBP',
		   'NPOF', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PAZA', 'PHOR', 'PIKK', 'PLZL', 'PMSB',
		   'PMSBP', 'POGR', 'POLY', 'PRMB', 'QIWI', 'RASP', 'RAVN', 'RBCM', 'RDRB', 'RGSS', 'RKKE', 'RNFT', 'ROLO',
		   'ROSB', 'ROSN', 'ROST', 'RSTI', 'RSTIP', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUGR',
		   'RUSI',
		   'RUSP', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SELGP', 'SFIN', 'SIBN',
		   'SLEN',
		   'SMLT', 'SNGS', 'SNGSP', 'STSB', 'STSBP', 'SVAV', 'SVET', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG',
		   'TGKA',
		   'TGKB', 'TGKBP', 'TGKD', 'TGKDP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRCN', 'TRFM', 'TRMK', 'TRNFP',
		   'TTLK',
		   'TUZA', 'UCSS', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKA', 'URKZ', 'USBN', 'UTAR', 'UWGN', 'VGSB', 'VGSBP',
		   'VJGZ', 'VJGZP', 'VLHZ', 'VRSB', 'VRSBP', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'VZRZ', 'VZRZP', 'WTCM',
		   'WTCMP',
		   'YAKG', 'YKEN', 'YKENP', 'YNDX', 'YRSB', 'YRSBP', 'ZILL', 'ZVEZ']
